### ISSUE TITLE
Noam's idle thoughts on next version of model

### ISSUE THREAD

**Issue by emmamendelsohn** [ecohealthalliance/open-rvfcast#4]
From @noamross 
https://github.com/ecohealthalliance/RVF-EWS/issues/40

Just some things I thought of on the train:

We should probably drop/avoid explicit geographical variables like lat, lon, country, and region-specific land use or cover categorizations. These preclude testing the applicability of the model to other areas using [distance index or area of applicability techniques](https://ecoevo.social/@MikeMahoney218@fosstodon.org/109740648097959548). Using a historical outbreak layer has the same issue.

Continuing down the road of DI/AoA: One way to evaluate whether a prediction is within the training set is to calculate the point density estimate of the new data point. But the data set is high-dimesional, so it's not as simple as density(). Vine copulas can do a nice job: https://github.com/vinecopulib/rvinecopulib. Fit a distibution with vine() and evaluate new density with dvine(), or simulate new data (including categorical, with some tweaking), with rvine().
Similarly, we may want to avoid using GLW, or at least use it in a way that separate it from other variables with https://github.com/vdorie/dbarts/issues/9, because this precludes interrogating the model to whether a region would be prone to rift but maybe doesn't have a the livestock that would result in outbreaks.

Instead of x, y, etc., we can add a number of static layers: BIOCLIM variables, forest cover, [grassland indices](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.16174), soil/geology/vegetation types, elevation (plus slope and aspect, which tell you something about hydrology). This way we can understand the similarity of regions outside our training zone.

A good way to understand the utility of these and also control model and data size is to collapse all the continuous static layers via PCA or a similar reduction.
This makes me consider some other, interpretable model structures (something like geographically-weighted regression, but weighting dynamic layers based on the PCA-collapsed static layers). It's speculation but suggests we should have a workflow as we do elsewhere that lets us swap out, test and compare different model back-ends as we do in other projects.

**Comment by n8layman** [comment]
Closed during June wrap up for DTRA
